# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/quarto_template',
                'doc_host': 'https://githubpsyche.github.io',
                'git_url': 'https://github.com/githubpsyche/quarto_template',
                'lib_path': 'quarto_template'},
  'syms': { 'quarto_template.helpers': { 'quarto_template.helpers.plot_polar': ( 'library/index.html#plot_polar',
                                                                                 'quarto_template/helpers.py')}}}
