# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/pnr.ipynb.

# %% auto 0
__all__ = ['fixed_pres_pnr', 'pnr', 'plot_pnr']

# %% ../notebooks/pnr.ipynb 2
from typing import Optional, Sequence

import jax.numpy as jnp
from jax import jit, vmap
from matplotlib import rcParams  # type: ignore
from matplotlib.axes import Axes

from ..experimental.plotting import init_plot, plot_data, set_plot_labels
from ..experimental.repetition import all_study_positions
from ..helpers import apply_by_subject, find_max_list_length
from ..typing import Array, Bool, Float, Integer


# %% ../notebooks/pnr.ipynb 4
def fixed_pres_pnr(
    recalls: Integer[Array, " trial_count recall_positions"],
    list_length: int,
    query_recall_position: int = 0,
) -> Float[Array, " study_positions"]:
    """Returns probability of nth recall as a function of study position, assuming uniform study lists.

    Args:
        recalls: trial by recall position array of recalled items. 1-indexed; 0 for no recall.
        list_length: the length of the study list.
        query_recall_position: Which recall index (0-based) to analyze (e.g., 0 for first recall).
    """
    # Identify the item recalled at the query_recall_position for each trial.
    # Bin counts for each item number, ignoring 0 (no recall).
    # Divide by the total number of trials to get a probability.
    return jnp.bincount(
        recalls[:, query_recall_position].flatten(), length=list_length + 1
    )[1:] / len(recalls)


# %% ../notebooks/pnr.ipynb 6
def pnr(
    recalls: Integer[Array, " trial_count recall_positions"],
    presentations: Integer[Array, " trial_count study_positions"],
    list_length: int,
    size: int = 3,
    query_recall_position: int = 0,
) -> Float[Array, " study_positions"]:
    """Returns probability of nth recall as a function of study position, allowing item repetitions.

    Args:
        recalls: trial by recall position array of recalled items. 1-indexed; 0 for no recall.
        presentations: trial by study position array of presented items. 1-indexed.
        list_length: the length of the study list.
        size: maximum number of study positions an item can be presented at.
        query_recall_position: Which recall index (0-based) to analyze (e.g., 0 for first recall).
    """
    # expanded_recalls: (trial_count, recall_positions, size) array
    # where each recalled item is mapped to all its possible study positions.
    expanded_recalls = vmap(
        vmap(all_study_positions, in_axes=(0, None, None)), in_axes=(0, 0, None)
    )(recalls, presentations, size)
    return fixed_pres_pnr(expanded_recalls, list_length, query_recall_position)


# %% ../notebooks/pnr.ipynb 8
def plot_pnr(
    datasets: Sequence[dict[str, jnp.ndarray]] | dict[str, jnp.ndarray],
    trial_masks: Sequence[Bool[Array, " trial_count"]] | Bool[Array, " trial_count"],
    query_recall_position: int = 0,
    distances: Optional[Float[Array, "word_count word_count"]] = None,
    color_cycle: Optional[list[str]] = None,
    labels: Optional[Sequence[str]] = None,
    contrast_name: Optional[str] = None,
    axis: Optional[Axes] = None,
    size: int = 3,
) -> Axes:
    """Returns Axes object with plotted probability of nth recall for given datasets and trial masks.

    Args:
        datasets: Datasets containing trial data to be plotted.
        trial_masks: Masks to filter trials in datasets.
        query_recall_position: Which recall index (0-based) to plot (e.g., 0 for first recall).
        distances: Unused, included for compatibility with other plotting functions.
        color_cycle: List of colors for plotting each dataset.
        labels: Names for each dataset for legend, optional.
        contrast_name: Name of contrast for legend labeling, optional.
        axis: Existing matplotlib Axes to plot on, optional.
        size: Maximum number of study positions an item can be presented at.
    """
    axis = init_plot(axis)

    if color_cycle is None:
        color_cycle = [each["color"] for each in rcParams["axes.prop_cycle"]]

    if labels is None:
        labels = [""] * len(datasets)

    # Convert single dict or single mask to list
    if isinstance(datasets, dict):
        datasets = [datasets]
    if isinstance(trial_masks, jnp.ndarray):
        trial_masks = [trial_masks]

    # Determine x-axis length
    max_list_length = find_max_list_length(datasets, trial_masks)

    # For each dataset, apply the pnr function by subject, gather results, and plot
    for data_index, data in enumerate(datasets):
        subject_values = jnp.vstack(
            apply_by_subject(
                data,
                trial_masks[data_index],
                jit(pnr, static_argnames=("size", "list_length")),
                size,
                query_recall_position,
            )
        )

        color = color_cycle.pop(0)
        plot_data(
            axis,
            jnp.arange(max_list_length, dtype=int) + 1,
            subject_values,
            labels[data_index],
            color,
        )

    set_plot_labels(axis, "Study Position", "Probability of Nth Recall", contrast_name)
    return axis
