project:
  type: manuscript
  output-dir: ../../docs/cru_to_cmr
  render: 
    - index.qmd

manuscript:
  code-links: repo

execute:
  freeze: auto

format:
  html:
    toc: true
    theme: darkly
    include-before-body:
      - text: "The authors are grateful to Gordan Logan and Adam Osth for their constructive feedback on earlier versions of this manuscript."
  apaquarto-pdf:
    nocorrespondence: true
    donotrepeattitle: true
    draftfirst: true
    filters:
      - abstract-section
