project:
  type: default
  output-dir: _output

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    fig-responsive: true
    self-contained: true

bibliography: references.bib
