# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/context.ipynb.

# %% auto 0
__all__ = ['TemporalContext']

# %% ../../notebooks/context.ipynb 2
import base64
import io

import matplotlib.pyplot as plt
from jax import numpy as jnp
from simple_pytree import Pytree

from ..math import normalize_magnitude
from ..state_analysis import matrix_heatmap
from ..typing import Array, Float, Float_


class TemporalContext(Pytree):
    """Temporal context representation for memory search models.

    The `TemporalContext` class implements the drifting, unit-length context representation used by 
    CMR-style models.

    The vector starts with a *start-of-list* unit (index 0) set to 1.0 and one unit per study item
    initialised to 0. On every call to `integrate`, the context drifts toward a normalised
    input vector while remaining unit-length. This initial state is preserved to enable
    drift back to the start-of-list context unit.

    An optional out-of-list context unit (index `item_count + 1`) can be used to simulate post-study
    drift, but unless the drift rate is near 1.0, it does not affect behavior: CMR relies on
    relative differences between context units, which remain unchanged.
    """

    def __init__(self, item_count: int, size: int):
        """Create a new temporal context model.

        Args:
            item_count: the number of items in the context model.
            size: the size of the context representation.
        """
        self.size = size
        self.zeros = jnp.zeros(size)
        self.state = self.zeros.at[0].set(1)
        self.initial_state = self.zeros.at[0].set(1)
        self.next_outlist_unit = item_count + 1

    @classmethod
    def init(cls, item_count: int) -> "TemporalContext":
        """Standardized initialization for a new context model.

        Args:
            item_count: the number of items in the context model.
        """
        return cls(item_count, item_count + 1)

    def integrate(
        self,
        context_input: Float[Array, " context_feature_units"],
        drift_rate: Float_,
    ) -> "TemporalContext":
        """Returns context after integrating input representation, preserving unit length.

        Args:
            context_input: the input representation to be integrated into the contextual state.
            drift_rate: The drift rate parameter.
        """
        context_input = normalize_magnitude(context_input)
        rho = jnp.sqrt(
            1 + jnp.square(drift_rate) * (jnp.square(self.state * context_input) - 1)
        ) - (drift_rate * (self.state * context_input))
        return self.replace(
            state=normalize_magnitude((rho * self.state) + (drift_rate * context_input))
        )

    def _repr_markdown_(self):
        """Returns a markdown representation of the context model."""
        fig, ax = matrix_heatmap(self.state, figsize=(6, 0.6))

        ax.set_xlabel("")
        ax.set_ylabel("")
        ax.set_yticks([])

        # Remove colorbar safely if desired:
        for coll in ax.collections:
            if hasattr(coll, "colorbar") and coll.colorbar:
                coll.colorbar.remove()

        buf = io.BytesIO()
        fig.savefig(buf, format="png", bbox_inches="tight")
        plt.close(fig)

        encoded = base64.b64encode(buf.getvalue()).decode("utf-8")
        return f'<img src="data:image/png;base64,{encoded}" />'

    @property
    def outlist_input(self) -> Float[Array, " context_feature_units"]:
        """Return the out-of-list context input."""
        return self.zeros.at[self.next_outlist_unit].set(1)

    def integrate_with_outlist(
        self,
        inlist_input: Float[Array, " context_feature_units"],
        ratio: Float_,
        drift_rate: Float_,
    ) -> "TemporalContext":
        """Integrates in-list context input with out-of-list context.

        Will produce errors if no out-of-list context units are available.

        Args:
            inlist_input: the input representation to be integrated into the contextual state.
            ratio: the ratio of out-of-list context to in-list context.
            drift_rate: The drift rate parameter.
        """
        context_input = normalize_magnitude(
            (normalize_magnitude(inlist_input) * ratio)
            + (self.outlist_input * (1 - ratio))
        )
        rho = jnp.sqrt(
            1 + jnp.square(drift_rate) * (jnp.square(self.state * context_input) - 1)
        ) - (drift_rate * (self.state * context_input))
        return self.replace(
            state=normalize_magnitude(
                (rho * self.state) + (drift_rate * context_input)
            ),
            next_outlist_unit=self.next_outlist_unit + 1,
        )

    @classmethod
    def init_expanded(cls, item_count: int) -> "TemporalContext":
        """Initialize a new context model with room for out-of-list contexts.

        Args:
            item_count: the number of items in the context model.
        """
        return cls(item_count, item_count + item_count + 1)

