project:
  type: manuscript
  output-dir: ../../docs/TalmiEEG
  render: 
    - index.qmd
    - "!render.ipynb"
    - "!Behaviour_and_Relationship_to_LPP.Rmd"

execute:
  freeze: true

format:
  html:
    theme: darkly
    toc: true
    comments:
      hypothesis: true
  docx: default