project:
  type: manuscript
  output-dir: ../../../docs/projects/bug_report

manuscript:
  article: index.ipynb

execute:
  echo: true

format:
  html:
    code-tools: true
    toc: true
    toc-depth: 3
    theme: cosmo
