# AUTOGENERATED! DO NOT EDIT! File to edit: ../src/analyses/00_Analyses.ipynb.

# %% auto 0
__all__ = ['recall_by_all_study_positions', 'fast_sem_crp', 'plot_sem_crp', 'single_pres_crp', 'multi_pres_crp', 'masked_crp', 'plot_crp', 'neighbor_contiguity', 'plot_neighbor_contiguity', 'single_pres_pfr', 'multi_pres_pfr', 'plot_pfr', 'single_pres_spc', 'multi_pres_spc', 'plot_spc', 'recall_probability_by_lag', 'find_max_lag', 'plot_recall_probability_by_lag', 'plot_lohnas_recall_probability_by_lag']

# %% ../src/analyses/00_Analyses.ipynb 3
import numpy as np
# from numba import njit

# @njit(nogil=True)
def recall_by_all_study_positions(
    recall_by_first_study_position, # Integer array where rows correspond go trials and columns to recall positions. Non-zero values identify a (1-indexed) study position of the item recalled at that position.  
    presentations, # Integer array where rows correspond to trials and columns to study positions. Non-zero values identify the unique index of the item presented at that position.
    max_repeats=3 # Maximum number of times we will expect an item to be repeated in a study sequence.
    ):
    """
    Identifies all study positions of each item in a set of presentation sequences and sorts them by recall position.

    Returns a 3D array where the first dimension corresponds to the maximum number of times an item may have been repeated in a study sequence, the second to trial_index, and the third to recall position. Non-zero values along the first dimension identify the (1-index) study position(s) of the item recalled at that position.
    """
    
    trials_shape = np.shape(recall_by_first_study_position)
    result = np.zeros(
            (max_repeats, trials_shape[0], trials_shape[1]), dtype=np.int32)

    for trial_index in range(len(recall_by_first_study_position)):

        trial = recall_by_first_study_position[trial_index]
        presentation = presentations[trial_index]
        
        for recall_index in range(len(trial)):

            if trial[recall_index] == 0:
                continue

            presentation_positions = np.nonzero(
                presentation[trial[recall_index] - 1] == presentation)[0] + 1

            result[:len(presentation_positions), trial_index, recall_index] = presentation_positions

    return result

# %% ../src/analyses/Distance_Contiguity_Effect.ipynb 3
# from numba import njit
import numpy as np

# @njit(nogil=True)
def fast_sem_crp(
    trials: np.ndarray, # 2D Integer array. Non-zero values are the (1-indexed) single study position of the item recalled at that position in the row's trial.
    distances: np.ndarray, # 3D array, entry (i,j,k) is the distance between the jth and kth items in the ith trial.
    item_counts: np.ndarray, # vector, entry (i) represents the number of unique items presented in the ith trial
    edges # vector specifying the edges of the bins for the distance distribution
    ):
    
    total_actual_transitions = np.zeros(len(edges))
    total_possible_transitions = np.zeros(len(edges))
    terminus = np.sum(trials != 0, axis=1)

    # tabulate bin totals for actual and possible distance transitions
    for trial_index in range(len(trials)):
        previous_item = 0
        possible_items = np.arange(item_counts[trial_index])

        # track possible and actual transitions across recalls
        for recall_index in range(terminus[trial_index]):
            current_item = trials[trial_index, recall_index]-1

            if recall_index > 0:

                # compute edge bin for distance between previous and each possible item
                index = 0
                for possible_index in range(len(possible_items)):
                    possible_item = possible_items[possible_index]
                    distance = distances[trial_index, possible_item, previous_item]
                    distance_bin = np.sum(edges < distance, dtype=np.int32)
                    total_possible_transitions[distance_bin] += 1
                    if possible_item == current_item:
                        total_actual_transitions[distance_bin] += 1

            # update pool to exclude recalled item (updated to still identify 1-indexed item)
            previous_item = current_item
            possible_items = possible_items[possible_items != previous_item]

    return total_actual_transitions/total_possible_transitions

# %% ../src/analyses/Distance_Contiguity_Effect.ipynb 6
import matplotlib.pyplot as plt
from scipy.stats import bootstrap
# from sentence_transformers import util
import warnings

def plot_sem_crp(
    datasets, # sequence of dataset structures for plotting
    trial_masks,  # vectors to filter datasets by
    string_embeddings, # sequence of string embeddings for plotting
    labels=None,  # sequence of names for each dataset to use in the legend
    contrast_name=None,  # name of the contrast to use in the legend
    axis=None # `matplotlib` axis object to plot on
    ):

    if axis is None:
        plt.figure()
        axis = plt.gca()

    if labels is None:
        labels = [''] * len(datasets)

    result = []
    for data_index, data in enumerate(datasets):

        # generate and subset trials array and list of list_lengths based on trial_query
        trial_mask = trial_masks[data_index]
        trials = data['recalls']
        list_lengths = data['listLength']
        string_ids = data['pres_itemids']
        subjects = data['subject'].flatten()

        # set edges based on distances between unique string_ids in current dataset
        if data_index == 0:
            distances = 1-util.pytorch_cos_sim(string_embeddings, string_embeddings).numpy()
            distances = np.maximum(0, distances)
            distances[np.eye(len(distances), dtype=int)] = np.nan
            edges = np.nanpercentile(distances, np.linspace(1, 100, 10))

        subject_crps = [] #np.zeros((len(np.unique(subjects)), len(edges)))

        for subject_index, subject in enumerate(np.unique(subjects)):
            subject_specific_trial_mask = np.logical_and(subjects==subject, trial_mask)
            if np.sum(subject_specific_trial_mask) == 0:
                continue

            subject_list_lengths = list_lengths[subject_specific_trial_mask].flatten()
            max_list_length = np.max(subject_list_lengths)

            # compute distances over sampled trials
            distances = np.zeros((np.sum(subject_specific_trial_mask), max_list_length, max_list_length))

            for trial_index, trial in enumerate(trials[subject_specific_trial_mask]):
                trial_embeddings = string_embeddings[string_ids[subject_specific_trial_mask][
                        trial_index, :subject_list_lengths[trial_index]]-1]
                cosine_scores = 1-util.pytorch_cos_sim(trial_embeddings, trial_embeddings).numpy()
                cosine_scores = np.maximum(0, cosine_scores)
                np.fill_diagonal(cosine_scores, np.nan)
                distances[trial_index, :len(trial_embeddings), :len(trial_embeddings)] = cosine_scores
                
            subject_crps.append(fast_sem_crp(
                trials[subject_specific_trial_mask], distances, subject_list_lengths, edges))

        subject_crps = np.array(subject_crps)
        crp_mean = np.nanmean(subject_crps, axis=0)

        if len(subject_crps) > 1:
            errors = np.zeros((2, len(crp_mean)))
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                bootstrapped_confidence_intervals = bootstrap((subject_crps,), np.mean).confidence_interval
            errors[0] = crp_mean - bootstrapped_confidence_intervals.low
            errors[1] = bootstrapped_confidence_intervals.high - crp_mean
            axis.errorbar(edges, crp_mean, errors, label=labels[data_index])
        else:
            axis.plot(edges, crp_mean, label=labels[data_index])
    
    axis.set(xlabel='Semantic Distance', ylabel='Conditional Recall Rate')

    if contrast_name:
        axis.legend(title=contrast_name)

    return axis

# %% ../src/analyses/Lag_Contiguity_Effect.ipynb 4
import numpy as np
# from numba import njit

# @njit(fastmath=True, nogil=True)
def single_pres_crp(
    recalls, # Integer array where rows correspond to trials and columns to recall positions. Non-zero values are the (1-indexed) single study position of the item recalled at that position.
    list_length, # Number of item presentations in each study sequence
):
    """
    Assuming each study sequence has no more than a single presentation of each item, returns a vector of length `(list_length - 1) * 2 + 1` containing the recall rate for each lag from `-(list_length - 1)` to `list_length - 1`, with the recall rate for lag 0 in the middle of the vector and set to the value 0 despite being undefined (since lag transitions of 0 are not possible).
    """

    lag_range = list_length - 1
    total_actual_lags = np.zeros(lag_range * 2 + 1)
    total_possible_lags = np.zeros(lag_range * 2 + 1)
    terminus = np.sum(recalls != 0, axis=1)

    # compute actual serial lag b/t recalls
    actual_lags = recalls[:, 1:] - recalls[:, :-1]
    actual_lags += lag_range

    # tabulate bin totals for actual and possible lags
    for i in range(len(recalls)):
        possible_items = np.arange(list_length) + 1
        previous_item = 0

        for recall_index in range(terminus[i]):

            # track possible and actual lags
            if recall_index > 0:
                total_actual_lags[actual_lags[i, recall_index - 1]] += 1

                # exploit equivalence b/t item index and study position to track possible lags
                possible_lags = possible_items - previous_item
                possible_lags += lag_range
                total_possible_lags[possible_lags] += 1

            # update pool of possible items to exclude recalled item
            previous_item = recalls[i, recall_index]
            possible_items = possible_items[possible_items != previous_item]

    # small correction to avoid nans
    total_possible_lags[total_actual_lags == 0] += 1

    return total_actual_lags / total_possible_lags

# %% ../src/analyses/Lag_Contiguity_Effect.ipynb 5
# @njit(nogil=True)
def multi_pres_crp(
    recalls, # Integer array where rows correspond to trials and columns to recall positions. Non-zero values identify a (1-indexed) study position of the item recalled at that position.
    presentations, # Integer array where rows correspond to trials and columns to study positions. Non-zero values identify the unique index of the item presented at that position.
    list_length # Number of item presentations in each study sequence
    ):
    """
    Calculate recall rate by lag across trials without the assumption that each study sequence has no more than a single presentation of each item. 
    
    Returns a vector of length `(list_length - 1) * 2 + 1` containing the recall rate for each lag indicing from `-(list_length - 1)` to `list_length - 1`, with the recall rate for lag 0 in the middle of the vector and set to the value 0 despite being undefined (since lag transitions of 0 are not possible). This function is slower than `single_pres_crp`, but it can be used with data where the single presentation assumption does not hold.
    """

    max_repeats = int(
        np.ceil(np.max(np.bincount(presentations.ravel()) / len(presentations)))
    )
    lag_range = list_length - 1
    total_actual_lags = np.zeros(lag_range * 2 + 1)
    total_possible_lags = np.zeros(lag_range * 2 + 1)
    terminus = np.sum(recalls != 0, axis=1)  # number of recalls per trial
    recall_by_study_position = recall_by_all_study_positions(
        recalls, presentations, max_repeats
    )

    for trial_index in range(len(recalls)):

        previous_item = 0
        item_count = np.max(presentations[trial_index])
        possible_items = np.arange(
            item_count,
            dtype=np.int32,
        )+1  # initial pool of possible recalls, 1-indexed
        possible_positions = np.zeros((item_count, max_repeats), dtype=np.int32)

        # we track possible positions using presentations and alt_presentations
        for item in range(item_count):
            pos = np.nonzero(presentations[trial_index] == item+1)[0] + 1
            possible_positions[item, :len(pos)] = pos

        for recall_index in range(terminus[trial_index]):

            current_item = presentations[trial_index][
                recalls[trial_index, recall_index] - 1
            ]

            # track possible and actual lags
            if recall_index > 0:

                # item indices don't help track lags anymore
                # so more complex calculation needed to identify possible lags given previous item
                current_index = np.nonzero(possible_items == current_item)[0]
                possible_lags = np.zeros(
                    (len(recall_by_study_position) ** 2, len(possible_items)),
                    dtype=np.int32,
                )

                index = 0
                for x in range(len(recall_by_study_position)):
                    for y in range(len(recall_by_study_position)):
                        if possible_positions[previous_item-1, y] > 0:

                            possible_lags[index] = (
                                possible_positions[possible_items-1, x]
                                - possible_positions[previous_item-1, y]
                            )

                            # if tracked position is 0, then we don't actually want to count it in our lags
                            possible_lags[index][
                                possible_positions[possible_items-1, x] == 0
                            ] = 0

                        index += 1
                possible_lags += lag_range

                total_actual_lags[possible_lags[:, current_index].flatten()] += 1
                total_possible_lags[possible_lags.flatten()] += 1

            # update pool to exclude recalled item (updated to still identify 1-indexed item)
            previous_item = current_item
            possible_items = possible_items[possible_items != previous_item]

    # small correction to avoid nans and commit to excluding multiply-tracked single presentations
    total_actual_lags[lag_range] = 0
    total_possible_lags[total_actual_lags == 0] += 1

    return total_actual_lags / total_possible_lags


# %% ../src/analyses/Lag_Contiguity_Effect.ipynb 6
# @njit(fastmath=True, nogil=True)
def masked_crp(
    trials, # Integer array where rows correspond to trials and columns to recall positions. Non-zero values identify a (1-indexed) study position of the item recalled at that position.
    list_length, # Number of item presentations in each study sequence
    mask # Boolean array where rows correspond to trials and columns to recall positions. True values indicate that the recall at that position should be included in the calculation.
    ):
    
    lag_range = list_length - 1
    total_actual_lags = np.zeros(lag_range * 2 + 1)
    total_possible_lags = np.zeros(lag_range * 2 + 1)
    terminus = np.sum(trials != 0, axis=1)
    
    # compute actual serial lag b/t recalls
    actual_lags = trials[:, 1:] - trials[:, :-1]
    actual_lags += lag_range
    
    # tabulate bin totals for actual and possible lags
    for i in range(len(trials)):
        possible_items = np.arange(list_length) + 1
        previous_item = 0
        
        for recall_index in range(terminus[i]):
            
            # track possible and actual lags
            if recall_index > 0 and mask[i, recall_index-1]:
                total_actual_lags[actual_lags[i, recall_index-1]] += 1
                
                # exploit equivalence b/t item index and study position to track possible lags
                possible_lags = possible_items - previous_item 
                possible_lags += lag_range
                total_possible_lags[possible_lags] += 1
                
            # update pool of possible items to exclude recalled item
            previous_item = trials[i, recall_index]
            possible_items = possible_items[possible_items != previous_item]
    
    # small correction to avoid nans
    total_possible_lags[total_actual_lags==0] += 1
    
    return total_actual_lags/total_possible_lags

# %% ../src/analyses/Lag_Contiguity_Effect.ipynb 8
import matplotlib.pyplot as plt
from scipy.stats import bootstrap
import warnings

def plot_crp(
    datasets,  # sequence of strings identifying the relative paths of datasets to plot
    trial_masks, # vectors to filter datasets by
    labels=None,  # sequence of names for each dataset to use in the legend
    contrast_name=None,  # name of the contrast to use in the legend
    axis=None,  # `matplotlib` axis object to plot on
    max_lag=5,  # maximum lag to plot a recall rate for
    handle_repetitions=None,  # uses `multi_pres_crp` or `single_pres_crp` to calculate recall rates if boolean; otherwise tries to decide whether to use `multi_pres_crp` or `single_pres_crp` based on content of `presentations`
    mask=None,  # optional boolean array of same size as datasets' `presentations` that tracks lag-CRP in indices of `recalls` where corresponding index in mask is True
):
    """
    Generates a plot of the lag-CRP curve for the provided datasets and trial queries, optionally using the provided labels and contrast name in the legend. An axis object can be provided to plot on an existing figure. The maximum lag to plot can be specified, and the function can be told to use `multi_pres_crp` or `single_pres_crp` to calculate recall rates. If `mask` is provided, the lag-CRP to be plotted will be calculated only for the indices of `recalls` where the corresponding index in `mask` is True.
    """

    if axis is None:
        plt.figure()
        axis = plt.gca()

    if labels is None:
        labels = [""] * len(datasets)

    for data_index, data in enumerate(datasets):

        lag_interval = np.arange(-max_lag, max_lag + 1, dtype=np.int32)

        # generate and subset trials array and list of list_lengths based on trial_query
        trial_mask = trial_masks[data_index]
        trials = data["recalls"]
        presentations = data["pres_itemnos"]
        subjects = data["subject"].flatten()
        subject_crps = [] #np.zeros((len(np.unique(subjects)), len(lag_interval)))

        for subject_index, subject in enumerate(np.unique(subjects)):
            subject_specific_trial_mask = np.logical_and(
                subjects == subject, trial_mask
            )

            if np.sum(subject_specific_trial_mask) == 0:
                continue

            if mask is None:
                if handle_repetitions is None:
                    list_length = np.max(data["listLength"][trial_mask])
                    handle_repetitions = not (
                        presentations[trial_mask][:, :list_length]
                        == np.arange(list_length) + 1
                    ).all()

                if not handle_repetitions:
                    list_length = np.max(data["listLength"][trial_mask])
                    lag_range = list_length - 1
                    subject_crps.append(single_pres_crp(
                        trials[subject_specific_trial_mask], list_length
                    )[lag_range - max_lag : lag_range + max_lag + 1])
                else:
                    list_length = np.max(data["listLength"][trial_mask])
                    lag_range = list_length - 1
                    subject_crps.append(multi_pres_crp(
                        trials[subject_specific_trial_mask],
                        presentations[subject_specific_trial_mask],
                        list_length,
                    )[lag_range - max_lag : lag_range + max_lag + 1])
            else:
                list_length = np.max(data["presentations"][trial_mask])
                lag_range = list_length - 1
                subject_crps.append(masked_crp(
                    trials[subject_specific_trial_mask], list_length, mask
                    )[lag_range - max_lag : lag_range + max_lag + 1])

        subject_crps = np.array(subject_crps)
        subject_crps = np.delete(subject_crps, max_lag, axis=1)
        crp_mean = np.nanmean(subject_crps, axis=0)

        color=next(axis._get_lines.prop_cycler)['color']
        if len(subject_crps) > 1:
            errors = np.zeros((2, len(crp_mean)))
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                bootstrapped_confidence_intervals = bootstrap(
                    (subject_crps,), np.nanmean
                ).confidence_interval
            errors[0] = crp_mean - bootstrapped_confidence_intervals.low
            errors[1] = bootstrapped_confidence_intervals.high - crp_mean

            # plot error bar using plt.fill_between and bootstrap
            axis.errorbar(lag_interval[:max_lag], crp_mean[:max_lag], errors[:, :max_lag], label=labels[data_index], color=color)
            axis.errorbar(lag_interval[max_lag+1:], crp_mean[max_lag:], errors[:, max_lag:], color=color)
        else:
            axis.plot(lag_interval[:max_lag], crp_mean[:max_lag], label=labels[data_index], color=color)
            axis.plot(lag_interval[max_lag+1:], crp_mean[max_lag:], color=color)

    axis.set(xlabel="Lag", ylabel="Conditional Resp. Prob.")

    if contrast_name:
        axis.legend(title=contrast_name)

    return axis

# %% ../src/analyses/Neighbor_Contiguity.ipynb 4
import numpy as np
# from numba import njit

# @njit
def neighbor_contiguity(
    trials, # Integer array where rows correspond to trials and columns to recall positions. Non-zero values identify the first (1-indexed) study position of the item with that recall position.
    presentations, # Integer array where rows correspond to trials and columns to study positions. Non-zero values identify the unique index of the item presented at that position.
    max_repeats=2, # maximum times any item gets repeatedly presented in a trial
    min_lag=3 # minimum number of intervening items between study positions for a repeated item to be considered
    ):

    assert(len(presentations) == len(trials))
    assert(min_lag > 2)

    # 3D array tracking each presentation position of recalled item
    # shape is (repetition_index, trial_index, recall_position)
    terminus = np.sum(trials != 0, axis=1) # number of recalls per trial
    list_length = np.sum(presentations[0] != 0) # number of presentations in list
    total_possible_neighbor_transitions = 0
    total_actual_neighbor_transitions = 0

    # for each unique item presented in a trial, 
    # we compute a lag by identifying its first and second presentation positions
    # when a lag is greater than min_lag, we consider the item to be a repeated item
    # we seek out recalls of Si or Sj in corresponding trial recalls, then track the rate of transitions to Sj or Si
    for trial_index in range(len(trials)):

        # 1) track si and sj across repeated items in trial
        item_count = int(np.max(presentations[trial_index]))
        si = np.zeros((item_count, 2), dtype=np.int64)
        sj = np.zeros((item_count, 2), dtype=np.int64)

        for item in range(1, item_count+1):

            positions = np.nonzero(presentations[trial_index] == item)[0]
            if len(positions) > 1:
                lag = positions[1] - positions[0] - 1
            else:
                lag = -1

            if lag < min_lag:
                continue

            # as long as this never throws an error, 
            # we don't need special handling for when j occurs too late in list for sj to contain two items
            #assert np.all(positions < list_length - 2)
            si[item-1, :] = presentations[trial_index, positions[0]+1:positions[0]+3]
            sj[item-1, :] = presentations[trial_index, positions[1]+1:positions[1]+3]

        # 2) measure ratio of possible si/sj transitions to actual si/sj transitions across recall events in trial
        previous_item = 0
        possible_items = np.arange(item_count, dtype=np.int32)+1  # initial pool of possible recalls, 1-indexed
        for recall_index in range(terminus[trial_index]):

            current_item = presentations[trial_index][trials[trial_index, recall_index] - 1]
            
            if recall_index > 0:

                # if the previous item is in si or sj, we increment bins 
                # based on whether current item is in corresponding subset of sj or si
                possible_count = 0
                actual_count = 0

                si_match = np.nonzero(si == previous_item)[0]
                if len(si_match) > 0:
                    for possible_item in possible_items:
                        if possible_item in sj[si_match]:
                            possible_count += 1
                    if current_item in sj[si_match]:
                        actual_count += 1

                total_actual_neighbor_transitions += actual_count > 0

                actual_count = 0

                sj_match = np.nonzero(sj == previous_item)[0]
                if len(sj_match) > 0:
                    for possible_item in possible_items:
                        if possible_item in si[sj_match]:
                            possible_count += 1
                    if current_item in si[sj_match]:
                        actual_count += 1

                #assert(actual_count < 2)
                #assert(possible_count < 2)
                total_possible_neighbor_transitions += possible_count > 0
                total_actual_neighbor_transitions += actual_count > 0

            # update pool to exclude recalled item (updated to still identify 1-indexed item)
            previous_item = current_item
            possible_items = possible_items[possible_items != previous_item]

    return total_actual_neighbor_transitions / total_possible_neighbor_transitions

# %% ../src/analyses/Neighbor_Contiguity.ipynb 7
import matplotlib.pyplot as plt
from scipy.stats import bootstrap
import warnings

def plot_neighbor_contiguity(
    datasets, # sequence dataset structures to plot
    trial_masks, # vectors to filter datasets by for main analysis
    control_trial_masks=None, # vectors to filter datasets by for control analysis
    labels=None, # sequence of names for each dataset to use in the legend
    contrast_name=None, # name of the contrast to use in the legend
    axis=None, # `matplotlib` axis object to plot on
    control_recalls = None,
    control_experiment_count = 0,
    ):

    if axis is None:
        plt.figure()
        axis = plt.gca()

    if labels is None:
        labels = [''] * len(datasets)

    for data_index, data in enumerate(datasets):

        trial_mask = trial_masks[data_index]
        control_trial_mask = control_trial_masks[data_index]
        trials = data['recalls']
        list_length = np.max(data['listLength'][trial_mask])
        presentations = data['pres_itemnos'][:, :list_length]
        subjects = data["subject"].flatten()
        subject_ncs = [] #np.zeros((len(np.unique(subjects)), 1))
        subject_ctrl_ncs = [] #np.zeros((len(np.unique(subjects)), 1))

        for subject_index, subject in enumerate(np.unique(subjects)):
            subject_specific_trial_mask = np.logical_and(
                subjects == subject, trial_mask
            )
            ctrl_subject_specific_trial_mask = np.logical_and(
                subjects == subject, control_trial_mask
            )

            if np.sum(subject_specific_trial_mask) == 0:
                continue

            subject_ncs.append(neighbor_contiguity(trials[subject_specific_trial_mask], presentations[subject_specific_trial_mask]))

            results = []
            indices = np.arange(np.sum(ctrl_subject_specific_trial_mask))
            for i in range(100):
                np.random.shuffle(indices)
                try:
                    results.append(neighbor_contiguity(trials[ctrl_subject_specific_trial_mask][indices], presentations[subject_specific_trial_mask]))
                except ZeroDivisionError:
                    pass

            subject_ctrl_ncs.append(np.mean(results))

        subject_ncs = np.array(subject_ncs)
        nc_mean = np.mean(subject_ncs, axis=0)
        subject_ctrl_ncs = np.array(subject_ctrl_ncs)
        ctrl_nc_mean = np.mean(subject_ctrl_ncs, axis=0)

        if len(subject_ncs) > 1:
            errors = errors = np.zeros((2, 2))
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                bootstrapped_confidence_intervals = bootstrap((subject_ncs,), np.mean).confidence_interval 
            errors[0, 0] = nc_mean - bootstrapped_confidence_intervals.low
            errors[1, 0] = bootstrapped_confidence_intervals.high - nc_mean

            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                bootstrapped_confidence_intervals = bootstrap((subject_ctrl_ncs,), np.mean).confidence_interval 
            errors[0, 1] = ctrl_nc_mean - bootstrapped_confidence_intervals.low
            errors[1, 1] = bootstrapped_confidence_intervals.high - ctrl_nc_mean

            # plot error bar using plt.fill_between and bootstrap
            axis.errorbar(np.arange(2), [nc_mean, ctrl_nc_mean], errors, label=labels[data_index], ls='none', fmt='.', elinewidth=4, mew=5)

        else:
            axis.plot(np.arange(2), [nc_mean, ctrl_nc_mean], label=labels[data_index], ls='none', marker='.', markersize=10)
            
    axis.set_xticks(np.arange(2, dtype=np.int32)) 
    axis.set_xticklabels(["Mixed", "Relabeled Control"])
    if contrast_name:
        axis.legend(title=contrast_name)

    return axis

# %% ../src/analyses/Probability_of_First_Recall.ipynb 4
import numpy as np
# from numba import njit

# @njit(nogil=True)
def single_pres_pfr(
    recalls, # Integer array where rows correspond to trials and columns to recall positions. Non-zero values are the (1-indexed) single study position of the item recalled at that position.
    list_length # Number of item presentations in each study sequence
    ):
    """
    Assuming each study sequence has no more than a single presentation of each item, returns a vector of length `list_length` containing the recall rate by serial position across all provided `trials`.
    """
    return np.bincount(recalls[:, 0], minlength=list_length+1)[1:]/len(recalls)

# %% ../src/analyses/Probability_of_First_Recall.ipynb 5
# @njit(nogil=True)
def multi_pres_pfr(
    recalls, # Integer array where rows correspond to trials and columns to recall positions. Non-zero values identify a (1-indexed) study position of the item recalled at that position.
    presentations, # Integer array where rows correspond to trials and columns to study positions. Non-zero values identify the unique index of the item presented at that position.
    list_length # Number of item presentations in each study sequence
    ):
    """
    Calculate recall rate by serial position across trials without the assumption that each study sequence has no more than a single presentation of each item.

    This function is slower than `single_pres_spc`, but it can be used with data where the single presentation assumption does not hold.
    """

    result = np.zeros(list_length, dtype=np.int32)
    all_study_positions = recall_by_all_study_positions(recalls, presentations) 
    first_recalls = all_study_positions[:, :, :1]
    
    for trial_index in range(len(recalls)):
        for study_position in range(list_length):
            result[study_position] += study_position+1 in first_recalls[:,trial_index]
    
    return result/len(recalls)

# %% ../src/analyses/Probability_of_First_Recall.ipynb 7
import matplotlib.pyplot as plt
from scipy.stats import bootstrap
import warnings

def plot_pfr(
    datasets, # sequence of strings identifying the relative paths of datasets to plot
    trial_masks, # vectors to filter datasets by
    labels=None,  # sequence of names for each dataset to use in the legend
    contrast_name=None, # name of the contrast to use in the legend
    axis=None, # `matplotlib` axis object to plot on
    handle_repetitions=None
    ):
    """
    Generates a plot of the serial position curve for the provided datasets and trial queries, optionally using the provided labels and contrast name in the legend. An axis object can be provided to plot on an existing figure.
    """
    
    if axis is None:
        plt.figure()
        axis = plt.gca()

    if labels is None:
        labels = [''] * len(datasets)

    results = []
    for data_index, data in enumerate(datasets):

        # generate and subset trials array and list of list_lengths based on trial_query
        trial_mask = trial_masks[data_index]
        trials = data['recalls']
        list_length = np.max(data['listLength'][trial_mask])
        presentations = data['pres_itemnos'][:, :list_length]
        subjects = data['subject'].flatten()
        subject_pfrs = [] #np.zeros((len(np.unique(subjects)), list_length))

        for subject_index, subject in enumerate(np.unique(subjects)):
            subject_specific_trial_mask = np.logical_and(subjects==subject, trial_mask)

            if np.sum(subject_specific_trial_mask) == 0:
                continue

            if handle_repetitions is None:
                handle_repetitions = not (presentations[trial_mask][:, :list_length] == np.arange(list_length)+1).all()

            if not handle_repetitions:
                subject_pfrs.append(single_pres_pfr(trials[subject_specific_trial_mask], list_length))
            else:
                subject_pfrs.append(multi_pres_pfr(
                    trials[subject_specific_trial_mask], presentations[subject_specific_trial_mask], list_length))

        subject_pfrs = np.array(subject_pfrs)
        pfr_mean = np.mean(subject_pfrs, axis=0)

        if len(subject_pfrs) > 1:
            errors = np.zeros((2, len(pfr_mean)))
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                bootstrapped_confidence_intervals = bootstrap((subject_pfrs,), np.mean).confidence_interval 
            errors[0] = pfr_mean - bootstrapped_confidence_intervals.low
            errors[1] = bootstrapped_confidence_intervals.high - pfr_mean

            # plot error bar using plt.fill_between and bootstrap
            axis.errorbar(np.arange(1, list_length+1), pfr_mean, errors, label=labels[data_index])
        else:
            axis.plot(np.arange(1, list_length+1), pfr_mean, label=labels[data_index])

    axis.set(xlabel='Serial Position', ylabel='Probability of Recall') 
    axis.set(xlabel='Serial Position', ylabel='Probability of Recall') 
    if contrast_name:
        axis.legend(title=contrast_name)

    return axis

# %% ../src/analyses/Serial_Position_Effect.ipynb 4
import numpy as np
# from numba import njit

# @njit(nogil=True)
def single_pres_spc(
    recalls, # Integer array where rows correspond to trials and columns to recall positions. Non-zero values are the (1-indexed) single study position of the item recalled at that position.
    list_length # Number of item presentations in each study sequence
    ):
    """
    Assuming each study sequence has no more than a single presentation of each item, returns a vector of length `list_length` containing the recall rate by serial position across all provided `recalls`. This function can track occurrence rates by many other features if non-zero values in `recalls` are replaced with the appropriate feature index.
    """

    # flatten provided recalls matrix and count proportion of recalls at each index, ignoring index 0
    return np.bincount(recalls.flatten(), minlength=list_length+1)[1:]/len(recalls)

# %% ../src/analyses/Serial_Position_Effect.ipynb 5
# @njit(nogil=True)
def multi_pres_spc(
    recalls, # Integer array where rows correspond to trials and columns to recall positions. Non-zero values identify a (1-indexed) study position of the item recalled at that position.
    presentations, # Integer array where rows correspond to trials and columns to study positions. Non-zero values identify the unique index of the item presented at that position.
    list_length # Number of item presentations in each study sequence
    ):
    """
    Calculate recall rate by serial position across trials without the assumption that each study sequence has no more than a single presentation of each item.

    This function is slower than `single_pres_spc`, but it can be used with data where the single presentation assumption does not hold.
    """

    result = np.zeros(list_length, dtype=np.int32)
    all_study_positions = recall_by_all_study_positions(recalls, presentations) 

    for trial_index in range(len(recalls)):
        for study_position in range(list_length):
            result[study_position] += study_position+1 in all_study_positions[:,trial_index]
    
    return result/len(recalls)

# %% ../src/analyses/Serial_Position_Effect.ipynb 7
import matplotlib.pyplot as plt
from scipy.stats import bootstrap
import warnings

def plot_spc(
    datasets, # sequence of dataset structures for plotting
    trial_masks, # vectors to filter datasets by
    labels=None, # sequence of names for each dataset to use in the legend
    contrast_name=None, # name of the contrast to use in the legend
    axis=None, # `matplotlib` axis object to plot on
    handle_repetitions=None, # if False, use `single_pres_spc` even if `multi_pres_spc` is available
    ):
    """
    Generates a plot of the serial position curve for the provided datasets and trial queries, optionally using the provided labels and contrast name in the legend. An axis object can be provided to plot on an existing figure.
    """
    
    if axis is None:
        plt.figure()
        axis = plt.gca()

    if labels is None:
        labels = [''] * len(datasets)

    results = []
    for data_index, data in enumerate(datasets):

        # generate and subset trials array and list of list_lengths based on trial_query
        trial_mask = trial_masks[data_index]
        trials = data['recalls']
        list_length = np.max(data['listLength'][trial_mask])
        presentations = data['pres_itemnos'][:, :list_length]
        subjects = data['subject'].flatten()
        subject_spcs = []

        for subject_index, subject in enumerate(np.unique(subjects)):
            subject_specific_trial_mask = np.logical_and(subjects==subject, trial_mask)

            if np.sum(subject_specific_trial_mask) == 0:
                continue

            if handle_repetitions is None:
                handle_repetitions = not (presentations[trial_mask][:, :list_length] == np.arange(list_length)+1).all()

            if not handle_repetitions:
                subject_spcs.append(single_pres_spc(trials[subject_specific_trial_mask], list_length))
            else:
                subject_spcs.append(multi_pres_spc(
                    trials[subject_specific_trial_mask], presentations[subject_specific_trial_mask], list_length))
                if 'Massed' in labels[data_index]:
                    # set every other index in the spc to np.nan to avoid jittery plot
                    subject_spcs[-1][1::2] = np.nan

        subject_spcs = np.array(subject_spcs)
        spc_mean = np.mean(subject_spcs, axis=0)
        if len(subject_spcs) > 1:
            errors = np.zeros((2, len(spc_mean)))
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                bootstrapped_confidence_intervals = bootstrap((subject_spcs,), np.mean).confidence_interval 
            errors[0] = spc_mean - bootstrapped_confidence_intervals.low
            errors[1] = bootstrapped_confidence_intervals.high - spc_mean

            # plot error bar using plt.fill_between and bootstrap
            axis.errorbar(np.arange(1, list_length+1), spc_mean, errors, label=labels[data_index])
        else:
            axis.plot(np.arange(1, list_length+1), spc_mean, label=labels[data_index])

    axis.set(xlabel='Serial Position', ylabel='Probability of Recall') 
    if contrast_name:
        axis.legend(title=contrast_name)

    return axis

# %% ../src/analyses/Spacing_Effect.ipynb 4
# from numba import njit, prange
import numpy as np

# @njit(nogil=True, parallel=True)
def recall_probability_by_lag(
    recalls, # Integer array where rows correspond to trials and columns to recall positions. Non-zero values identify the first (1-indexed) study position of the item with that recall position.
    presentations, # Integer array where rows correspond to trials and columns to study positions. Non-zero values identify the unique index of the item presented at that position.
    max_lag=8 # maximum possible number of intervening items between repetitions
    ):
    
    assert(len(presentations) == len(recalls))
    total_presented, total_retrieved = np.zeros(max_lag+2), np.zeros(max_lag+2)

    # for each unique item presented in a trial, 
    # we compute a lag by identifying its first and second presentation positions
    # then increment the corresponding lag bins in the presented and retrieved vectors
    for trial_index in range(len(presentations)):
        presented, retrieved = np.zeros(max_lag+2), np.zeros(max_lag+2)
        trial = recalls[trial_index]
        trial = trial[trial > 0]-1
        
        for item in np.unique(presentations[trial_index]):
            if item == 0:
                continue

            positions = np.nonzero(presentations[trial_index] == item)[0]
            if len(positions) > 1:
                lag = positions[1] - positions[0] - 1
            else:
                lag = -1

            presented[lag+1] += 1 # we correct indices to be non-negative
            retrieved[lag+1] += positions[0] in trial
            
        total_presented += presented
        total_retrieved += retrieved

    return total_retrieved/total_presented

# %% ../src/analyses/Spacing_Effect.ipynb 5
# @njit(nogil=True, parallel=True)
def find_max_lag(
    presentations, # Integer array where rows correspond to trials and columns to study positions. Non-zero values identify the unique index of the item presented at that position.
    ):
    """
    Finds the maximum lag between repetitions of any item in the dataset.
    """

    max_lag = -1
    for trial_index in range(len(presentations)):
        for item in np.unique(presentations[trial_index]):
            if item == 0:
                continue

            for idx, val in np.ndenumerate(presentations[trial_index]):
                if val == item:
                    first_study_position = idx[0]
                    break

            lag = -1 # lag of -1 means the item was not repeated
            if first_study_position < len(presentations[trial_index]):
                for idx, val in np.ndenumerate(presentations[trial_index][first_study_position+1:]):
                    if val == item:
                        lag = idx[0]
                        break

            max_lag = max(max_lag, lag)

    return max(max_lag, -1)

# %% ../src/analyses/Spacing_Effect.ipynb 9
import matplotlib.pyplot as plt
from scipy.stats import bootstrap
import warnings

def plot_recall_probability_by_lag(
    datasets, # sequence dataset structures to plot
    trial_masks, # vectors to filter datasets by
    labels=None, # sequence of names for each dataset to use in the legend
    contrast_name=None, # name of the contrast to use in the legend
    axis=None # `matplotlib` axis object to plot on
    ):

    if axis is None:
        plt.figure()
        axis = plt.gca()

    if labels is None:
        labels = [''] * len(datasets)

    results = []
    for data_index, data in enumerate(datasets):

        # generate and subset trials array and list of list_lengths based on trial_query
        trial_mask = trial_masks[data_index]
        trials = data['recalls']
        presentations = data['pres_itemnos']
        max_lag = find_max_lag(presentations)
        subjects = data['subject'].flatten()
        subject_rpls = [] #np.zeros((len(np.unique(subjects)), max_lag+2))

        for subject_index, subject in enumerate(np.unique(subjects)):
            subject_specific_trial_mask = np.logical_and(subjects==subject, trial_mask)

            if np.sum(subject_specific_trial_mask) == 0:
                continue
            
            subject_rpls.append(recall_probability_by_lag(
                trials[subject_specific_trial_mask], presentations[subject_specific_trial_mask], max_lag))

        subject_rpls = np.array(subject_rpls)
        rpl_mean = np.mean(subject_rpls, axis=0)

        if len(subject_rpls) > 1:
            errors = np.zeros((2, len(rpl_mean)))
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                bootstrapped_confidence_intervals = bootstrap((subject_rpls,), np.mean).confidence_interval 
            errors[0] = rpl_mean - bootstrapped_confidence_intervals.low
            errors[1] = bootstrapped_confidence_intervals.high - rpl_mean

            # plot error bar using plt.fill_between and bootstrap
            axis.errorbar(np.arange(max_lag+2), rpl_mean, errors, label=labels[data_index])
        else:
            axis.plot(np.arange(max_lag+2), rpl_mean, label=labels[data_index])

    axis.set(xlabel='Number of Intervening Items', ylabel='Recall Probability') 
    axis.set(xlabel='Number of Intervening Items', ylabel='Recall Probability') 
    axis.set_xticks(np.arange(max_lag+2, dtype=np.int32))
    axis.set_xticklabels(['N/A'] + [str(i) for i in np.arange(max_lag+1, dtype=np.int32)])
    if contrast_name:
        axis.legend(title=contrast_name)

    return axis

# %% ../src/analyses/Spacing_Effect.ipynb 10
import matplotlib.pyplot as plt
from scipy.stats import bootstrap
import warnings

def plot_lohnas_recall_probability_by_lag(
    datasets, # sequence dataset structures to plot
    trial_masks, # vectors to filter datasets by
    labels=None, # sequence of names for each dataset to use in the legend
    contrast_name=None, # name of the contrast to use in the legend
    axis=None, # `matplotlib` axis object to plot on
    control_recalls = None,
    control_experiment_count = 0,
    ):

    lags = ['N/A', '0', '1-2', '3-5', '6-8']

    if axis is None:
        plt.figure()
        axis = plt.gca()

    if labels is None:
        labels = [''] * len(datasets)

    for data_index, data in enumerate(datasets):

        # generate and subset trials array and list of list_lengths based on trial_query
        trial_mask = trial_masks[data_index]
        trials = data['recalls']
        presentations = data['pres_itemnos']
        max_lag = find_max_lag(presentations)
        subjects = data['subject'].flatten()
        subject_rpls = [] #np.zeros((len(np.unique(subjects)), len(lags)))

        for subject_index, subject in enumerate(np.unique(subjects)):
            subject_specific_trial_mask = np.logical_and(subjects==subject, trial_mask)

            if np.sum(subject_specific_trial_mask) == 0:
                continue

            subject_result = recall_probability_by_lag(
                trials[subject_specific_trial_mask], presentations[subject_specific_trial_mask], max_lag)

            binned = np.zeros(5)
            binned[0] = subject_result[0]
            binned[1] = subject_result[1]
            binned[2] = (subject_result[2] + subject_result[3])/2
            binned[3] = (subject_result[4] + subject_result[5] + subject_result[6])/3
            binned[4] = (subject_result[7] + subject_result[8] + subject_result[9])/3
            
            subject_rpls.append(binned)

        subject_rpls = np.array(subject_rpls)
        rpl_mean = np.mean(subject_rpls, axis=0)

        errors = np.zeros((2, len(rpl_mean)))
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            bootstrapped_confidence_intervals = bootstrap((subject_rpls,), np.mean).confidence_interval 
        errors[0] = rpl_mean - bootstrapped_confidence_intervals.low
        errors[1] = bootstrapped_confidence_intervals.high - rpl_mean

        # plot error bar using plt.fill_between and bootstrap
        axis.errorbar(np.arange(len(rpl_mean)), rpl_mean, errors, label=labels[data_index], ls='none', fmt='.', elinewidth=4, mew=5)
        #axis.bar(np.arange(len(rpl_mean)), rpl_mean, label=labels[data_index])

    axis.set(xlabel='Number of Intervening Items', ylabel='Recall Probability') 
    axis.set(xlabel='Number of Intervening Items', ylabel='Recall Probability') 
    axis.set_xticks(np.arange(len(lags), dtype=np.int32))
    axis.set_xticklabels(lags)
    if contrast_name:
        axis.legend(title=contrast_name)

    return axis