# AUTOGENERATED! DO NOT EDIT! File to edit: ../src/library/00_index.ipynb.

# %% auto 0
__all__ = ['plot_polar']

# %% ../src/library/00_index.ipynb 2
#| code-summary: quarto hello world example as a function
import numpy as np
import matplotlib.pyplot as plt

def plot_polar(r):
    theta = 2 * np.pi * r
    fig, ax = plt.subplots(
    subplot_kw = {'projection': 'polar'} 
    )
    ax.plot(theta, r)
    ax.set_rticks([0.5, 1, 1.5, 2])
    ax.grid(True)
    plt.show()
